linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gosec
    - gocritic
    - misspell
    - revive

linters-settings:
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnecessaryBlock

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    # Exclude gosec G104 for test setup code
    - path: _test\.go
      linters:
        - gosec
      text: "G104:"
    # Exclude shadow warnings in tests (common pattern)
    - path: _test\.go
      linters:
        - govet
      text: "shadow:"
    # Exclude shadow warnings in BoltDB transactions (common nested error pattern)
    - linters:
        - govet
      text: "shadow:.*err"
    # Exclude fieldalignment warnings (performance optimization)
    - linters:
        - govet
      text: "fieldalignment:"
    # Exclude unused parameter in Cobra callbacks (required by framework)
    - path: cmd/root\.go
      linters:
        - revive
      text: "unused-parameter"
    # Exclude errcheck in test helpers
    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value"
    # Exclude integer overflow conversion in bit operations (intentional)
    - path: util/util\.go
      linters:
        - gosec
      text: "G115:"
    # Exclude unused k parameter in ForEach callbacks
    - linters:
        - revive
      text: "unused-parameter.*parameter 'k'"
